limitPerRun: 30

issues:
  daysUntilStale: 365
  daysUntilClose: 20
  exemptProjects: true
  exemptMilestones: true
  staleLabel: stale

  markComment: >
    This issue has been automatically marked as stale because
    it has not had activity from the community in the last year. It will be
    closed if no further activity occurs within 20 days.
  closeComment: >
    This issue has been automatically closed because it is has not had activity
    from the community in the last year.